env:
  browser: true
  es6: true
extends:
  - standard
rules:
  "no-unused-vars": "off"
  "@typescript-eslint/no-unused-vars":
    - "error"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - '@typescript-eslint'
